
package zodiac.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import org.apache.commons.lang3.StringUtils;
import zodiac.action.AssignmentAction;
import zodiac.definition.coursework.Assignment;

/**
 * Menu for editing an assignment.
 *
 * @author highzealot
 */
public class EditAssignmentMenu extends javax.swing.JFrame {

  private Assignment assignment;
  private javax.swing.JLabel titleLabel;
  private javax.swing.JLabel nameLabel;
  private javax.swing.JLabel maxLabel;
  private javax.swing.JTextField maxTextField;
  private javax.swing.JTextField nameTextField;
  private javax.swing.JButton okButton;
  private javax.swing.JButton saveMaxButton;
  private javax.swing.JButton saveNameButton;

  /**
   * Creates new form EditAssignmentMenu.
   */
  public EditAssignmentMenu(Assignment assignment) {
    initComponents();
    this.assignment = assignment;
    nameTextField.setText(assignment.getName());
    maxTextField.setText(assignment.getMaxAttempt() + "");

    saveNameButton.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent actionEvent) {
        JOptionPane.showMessageDialog(new JFrame(), "Nothing yet");
      }
    });

    saveMaxButton.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent actionEvent) {
        String input = StringUtils.trimToEmpty(maxTextField.getText());
        try {
          JOptionPane.showMessageDialog(new JFrame(), editMax(Integer.parseInt(input)));
        } catch (NumberFormatException e) {
          JOptionPane.showMessageDialog(new JFrame(), "Invalid input");
        }
      }
    });

    okButton.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent actionEvent) {
        close();
      }
    });
  }

  private String editMax(int max) {
    return new AssignmentAction().setAssignmentMaxAttempt(assignment, max);
  }

  private void close() {
    this.dispose();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {

    nameTextField = new javax.swing.JTextField();
    maxTextField = new javax.swing.JTextField();
    saveNameButton = new javax.swing.JButton();
    saveMaxButton = new javax.swing.JButton();
    okButton = new javax.swing.JButton();
    titleLabel = new javax.swing.JLabel();
    nameLabel = new javax.swing.JLabel();
    maxLabel = new javax.swing.JLabel();

    setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    setBackground(null);

    nameTextField.setText("jTextField1");

    maxTextField.setText("jTextField1");

    saveNameButton.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
    saveNameButton.setText("Save Name");

    saveMaxButton.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
    saveMaxButton.setText("Save Max");

    okButton.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
    okButton.setText("Close");

    titleLabel.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
    titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    titleLabel.setText("Edit Assignment");

    nameLabel.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
    nameLabel.setText("Name: ");

    maxLabel.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
    maxLabel.setText("Max Attempts:");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(okButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                        layout.createSequentialGroup()
                            .addGroup(layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(nameLabel)
                                        .addComponent(maxLabel))
                                    .addGap(6, 6, 6)
                                    .addComponent(maxTextField,
                                        javax.swing.GroupLayout.PREFERRED_SIZE, 235,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(saveMaxButton,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                    layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(nameTextField,
                                            javax.swing.GroupLayout.PREFERRED_SIZE, 235,
                                            javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(saveNameButton)))
                            .addGap(12, 12, 12)))
                .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveNameButton)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveMaxButton)
                    .addComponent(maxLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(okButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  } // </editor-fold>

}
